import express from 'express';
import validateRequest from '../../middlewares/validateRequest';
import { academicDepartmentSchemaValidations } from './academicDepartment.validation';
import { academicDepartmentControllers } from './academicDepartment.controller';
const router = express.Router();
router.post('/create-academic-department', validateRequest(academicDepartmentSchemaValidations.academicDepartmentSchema), academicDepartmentControllers.createAcademicDepartment);
router.get('/', academicDepartmentControllers.getAcademicDepartment);
router.get('/:id', academicDepartmentControllers.getSigngleAcademicDepartment);
router.patch('/:id', validateRequest(academicDepartmentSchemaValidations.updateAcademicDepartmentSchema), academicDepartmentControllers.updateAcademicDepartment);
export const academicDepartmentRoutes = router;
