import express from 'express';
import { academicFacultyControllers } from './academicFaculty.controller';
import validateRequest from '../../middlewares/validateRequest';
import { academicFacultySchemaValidation } from './academicFaculty.validation';
const router = express.Router();
router.post('/create-academic-faculty', validateRequest(academicFacultySchemaValidation.academicFacultySchema), academicFacultyControllers.createAcademicFaculty);
router.get('/',  academicFacultyControllers.getAcademicFaculty);
router.get('/:id', academicFacultyControllers.getSigngleAcademicFaculty);
router.patch('/:id', validateRequest(academicFacultySchemaValidation.updateAcademicFacultySchema), academicFacultyControllers.updateAcademicFaculty);
export const academicFacultyRoutes = router;
